"""create pontos verdes tables

Revision ID: 23aa922c00d6
Revises: 001_initial
Create Date: 2026-06-02 16:00:59.998009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23aa922c00d6'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Evita DuplicateObject ao recriar enums em ambientes que já rodaram migrações
    for enum_name in [
        "categoriapontoverde",
        "statuspontoverde",
        "statuscheckinpontoverde",
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_name} CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pontos_verdes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.Enum('praca', 'canteiro', 'praia', 'rio', 'outro', name='categoriapontoverde'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('guardiao_id', sa.UUID(), nullable=True),
    sa.Column('guardiao_name', sa.String(length=200), nullable=True),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('disponivel', 'ativo', 'alerta', 'concluido', name='statuspontoverde'), nullable=False),
    sa.Column('meses_concluidos', sa.Integer(), nullable=False),
    sa.Column('proximo_checkin_limite', sa.DateTime(timezone=True), nullable=True),
    sa.Column('foto_inicial_url', sa.String(length=500), nullable=True),
    sa.Column('nft_token_id', sa.Integer(), nullable=True),
    sa.Column('nft_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guardiao_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pontos_verdes_guardiao_id'), 'pontos_verdes', ['guardiao_id'], unique=False)
    op.create_index(op.f('ix_pontos_verdes_id'), 'pontos_verdes', ['id'], unique=False)
    op.create_index(op.f('ix_pontos_verdes_nft_tx_hash'), 'pontos_verdes', ['nft_tx_hash'], unique=False)
    op.create_table('checkins_pontos_verdes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ponto_verde_id', sa.UUID(), nullable=False),
    sa.Column('mes_referencia', sa.Integer(), nullable=False),
    sa.Column('data_envio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovado', 'rejeitado', name='statuscheckinpontoverde'), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ponto_verde_id'], ['pontos_verdes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_pontos_verdes_id'), 'checkins_pontos_verdes', ['id'], unique=False)
    op.create_index(op.f('ix_checkins_pontos_verdes_ponto_verde_id'), 'checkins_pontos_verdes', ['ponto_verde_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkins_pontos_verdes_ponto_verde_id'), table_name='checkins_pontos_verdes')
    op.drop_index(op.f('ix_checkins_pontos_verdes_id'), table_name='checkins_pontos_verdes')
    op.drop_table('checkins_pontos_verdes')
    op.drop_index(op.f('ix_pontos_verdes_nft_tx_hash'), table_name='pontos_verdes')
    op.drop_index(op.f('ix_pontos_verdes_id'), table_name='pontos_verdes')
    op.drop_index(op.f('ix_pontos_verdes_guardiao_id'), table_name='pontos_verdes')
    op.drop_table('pontos_verdes')

    for enum_name in [
        "statuscheckinpontoverde",
        "statuspontoverde",
        "categoriapontoverde",
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
