"""add_acoes_educacionais_and_nft_relation

Revision ID: 31fe9ab47dcd
Revises: bc4a637ed43e
Create Date: 2026-06-09 03:31:27.052394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31fe9ab47dcd'
down_revision: Union[str, None] = 'bc4a637ed43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acoes_educacionais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('autor_tipo', sa.Enum('cidadao', 'instituto', name='autortipo'), nullable=False),
    sa.Column('tipo_acao', sa.Enum('palestra', 'oficina', 'roda_conversa', 'mutirao_educativo', 'outro', name='tipoacaoeducativa'), nullable=False),
    sa.Column('num_pessoas', sa.Integer(), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'aprovada', 'rejeitada', name='statusacaoeducativa'), nullable=False),
    sa.Column('validado_por', sa.UUID(), nullable=True),
    sa.Column('validado_por_tipo', sa.Enum('cidadao', 'instituto', name='autortipo'), nullable=True),
    sa.Column('motivo_rejeicao', sa.Text(), nullable=True),
    sa.Column('registry_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('mint_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validado_por'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acoes_educacionais_autor_id'), 'acoes_educacionais', ['autor_id'], unique=False)
    op.create_index(op.f('ix_acoes_educacionais_id'), 'acoes_educacionais', ['id'], unique=False)
    op.create_index(op.f('ix_acoes_educacionais_validado_por'), 'acoes_educacionais', ['validado_por'], unique=False)
    op.add_column('nfts', sa.Column('educacao_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'nfts', 'acoes_educacionais', ['educacao_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nfts', type_='foreignkey')
    op.drop_column('nfts', 'educacao_id')
    op.drop_index(op.f('ix_acoes_educacionais_validado_por'), table_name='acoes_educacionais')
    op.drop_index(op.f('ix_acoes_educacionais_id'), table_name='acoes_educacionais')
    op.drop_index(op.f('ix_acoes_educacionais_autor_id'), table_name='acoes_educacionais')
    op.drop_table('acoes_educacionais')
    # ### end Alembic commands ###
