"""add_denuncias_table

Revision ID: bc4a637ed43e
Revises: 23aa922c00d6
Create Date: 2026-06-09 02:34:00.184331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4a637ed43e'
down_revision: Union[str, None] = '23aa922c00d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('denuncias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cidadao_id', sa.UUID(), nullable=False),
    sa.Column('tipo_problema', sa.Enum('descarte_ilegal', 'esgoto', 'queimada', 'poluicao_agua', 'poluicao_ar', 'desmatamento', 'outro', name='tipoproblema'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('foto_problema_url', sa.String(length=500), nullable=False),
    sa.Column('foto_resolucao_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('registrada', 'em_analise', 'resolvida', 'improcedente', name='statusdenuncia'), nullable=False),
    sa.Column('proof_hash', sa.String(length=255), nullable=True),
    sa.Column('blockchain_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('resolucao_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('motivo_improcedencia', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cidadao_id'], ['cidadaos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denuncias_cidadao_id'), 'denuncias', ['cidadao_id'], unique=False)
    op.create_index(op.f('ix_denuncias_id'), 'denuncias', ['id'], unique=False)
    op.drop_constraint(op.f('institutos_cnpj_key'), 'institutos', type_='unique')
    op.drop_index(op.f('ix_institutos_cnpj'), table_name='institutos')
    op.create_index(op.f('ix_institutos_cnpj'), 'institutos', ['cnpj'], unique=True)
    op.drop_constraint(op.f('nfts_token_id_key'), 'nfts', type_='unique')
    op.drop_constraint(op.f('nfts_tx_hash_key'), 'nfts', type_='unique')
    op.drop_index(op.f('ix_nfts_token_id'), table_name='nfts')
    op.create_index(op.f('ix_nfts_token_id'), 'nfts', ['token_id'], unique=True)
    op.drop_index(op.f('ix_nfts_tx_hash'), table_name='nfts')
    op.create_index(op.f('ix_nfts_tx_hash'), 'nfts', ['tx_hash'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_nfts_tx_hash'), table_name='nfts')
    op.create_index(op.f('ix_nfts_tx_hash'), 'nfts', ['tx_hash'], unique=False)
    op.drop_index(op.f('ix_nfts_token_id'), table_name='nfts')
    op.create_index(op.f('ix_nfts_token_id'), 'nfts', ['token_id'], unique=False)
    op.create_unique_constraint(op.f('nfts_tx_hash_key'), 'nfts', ['tx_hash'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('nfts_token_id_key'), 'nfts', ['token_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_institutos_cnpj'), table_name='institutos')
    op.create_index(op.f('ix_institutos_cnpj'), 'institutos', ['cnpj'], unique=False)
    op.create_unique_constraint(op.f('institutos_cnpj_key'), 'institutos', ['cnpj'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_denuncias_id'), table_name='denuncias')
    op.drop_index(op.f('ix_denuncias_cidadao_id'), table_name='denuncias')
    op.drop_table('denuncias')
    # ### end Alembic commands ###
